In [1]:
from network import MobileNetV2_search

In [9]:
MobileNetV2_search().state_dict()

OrderedDict([('first_conv.conv.weight',
              tensor([[[[ 0.0146, -0.0681, -0.0429],
                        [-0.0224, -0.1154, -0.1326],
                        [-0.1056, -0.0005, -0.0883]],
              
                       [[ 0.0040,  0.1621,  0.1447],
                        [ 0.0537,  0.0179,  0.0960],
                        [ 0.1348, -0.0598,  0.0852]],
              
                       [[-0.0677, -0.1700, -0.1184],
                        [-0.1687, -0.1379,  0.0387],
                        [ 0.0276,  0.1263,  0.1371]]],
              
              
                      [[[ 0.0823,  0.1610, -0.1375],
                        [-0.1307,  0.1035,  0.0468],
                        [-0.0947, -0.0458, -0.1584]],
              
                       [[ 0.0999, -0.1273,  0.0450],
                        [-0.1229, -0.0896,  0.1179],
                        [-0.1399, -0.1552,  0.0702]],
              
                       [[-0.0327, -0.0958,  0.1506],
                

In [5]:
import torch


In [7]:
torch.load('logs/baseline2/final_network.pth')['first_conv.conv.weight']

KeyError: 'first_conv.conv.weight'

In [8]:
torch.load('logs/baseline2/final_network.pth')

OrderedDict([('module.first_conv.conv.weight',
              tensor([[[[-3.4135e-02,  5.5735e-02,  8.8404e-02],
                        [ 1.7712e-01,  6.5656e-01,  6.6747e-01],
                        [ 2.0492e-01,  7.1888e-01,  6.7735e-01]],
              
                       [[ 6.8576e-02, -2.0557e-01, -2.2023e-01],
                        [-9.7463e-02, -3.1686e-01, -3.5672e-01],
                        [ 2.5280e-02, -6.8306e-02, -1.6665e-01]],
              
                       [[ 7.8855e-02,  3.8043e-02,  1.3397e-01],
                        [-2.5815e-01, -4.3975e-01, -3.9005e-01],
                        [-3.3877e-01, -5.0529e-01, -5.7885e-01]]],
              
              
                      [[[ 1.5859e-01,  1.5920e-01,  1.8378e-01],
                        [ 3.9206e-01,  4.3925e-01,  3.8141e-01],
                        [ 2.4505e-01,  3.4921e-01,  4.0125e-01]],
              
                       [[-2.9316e-01, -3.8502e-01, -2.8473e-01],
                        [-5.

In [14]:
pretrained_key_list = []

for key, val in torch.load('logs/baseline2/final_network.pth').items():
    print(key)
    pretrained_key_list.append(key)

module.first_conv.conv.weight
module.first_block_conv.depth_conv.conv.weight
module.first_block_conv.point_linear.conv.weight
module.features.0.0.inverted_bottleneck.conv.weight
module.features.0.0.depth_conv.conv.weight
module.features.0.0.point_linear.conv.weight
module.features.0.1.inverted_bottleneck.conv.weight
module.features.0.1.depth_conv.conv.weight
module.features.0.1.point_linear.conv.weight
module.features.0.2.inverted_bottleneck.conv.weight
module.features.0.2.depth_conv.conv.weight
module.features.0.2.point_linear.conv.weight
module.features.0.3.inverted_bottleneck.conv.weight
module.features.0.3.depth_conv.conv.weight
module.features.0.3.point_linear.conv.weight
module.features.0.4.inverted_bottleneck.conv.weight
module.features.0.4.depth_conv.conv.weight
module.features.0.4.point_linear.conv.weight
module.features.0.5.inverted_bottleneck.conv.weight
module.features.0.5.depth_conv.conv.weight
module.features.0.5.point_linear.conv.weight
module.features.1.0.inverted_bottl

In [13]:
model_key_list = []

for key, val in MobileNetV2_search().state_dict().items():
    print(key)
    model_key_list.append(key)

first_conv.conv.weight
first_block_conv.depth_conv.conv.weight
first_block_conv.point_linear.conv.weight
features.0.0.inverted_bottleneck.conv.weight
features.0.0.depth_conv.conv.weight
features.0.0.point_linear.conv.weight
features.0.1.inverted_bottleneck.conv.weight
features.0.1.depth_conv.conv.weight
features.0.1.point_linear.conv.weight
features.0.2.inverted_bottleneck.conv.weight
features.0.2.depth_conv.conv.weight
features.0.2.point_linear.conv.weight
features.0.3.inverted_bottleneck.conv.weight
features.0.3.depth_conv.conv.weight
features.0.3.point_linear.conv.weight
features.0.4.inverted_bottleneck.conv.weight
features.0.4.depth_conv.conv.weight
features.0.4.point_linear.conv.weight
features.0.5.inverted_bottleneck.conv.weight
features.0.5.depth_conv.conv.weight
features.0.5.point_linear.conv.weight
features.1.0.inverted_bottleneck.conv.weight
features.1.0.depth_conv.conv.weight
features.1.0.point_linear.conv.weight
features.1.1.inverted_bottleneck.conv.weight
features.1.1.dept

In [15]:
len(model_key_list)

384

In [16]:
len(pretrained_key_list)

384

In [27]:
refined_model_key_list = []

for key in model_key_list:
    refined_model_key_list.append('module.' + key)

In [28]:
pretrained_key_list == refined_model_key_list

True

In [29]:
refined_model_key_list

['module.first_conv.conv.weight',
 'module.first_block_conv.depth_conv.conv.weight',
 'module.first_block_conv.point_linear.conv.weight',
 'module.features.0.0.inverted_bottleneck.conv.weight',
 'module.features.0.0.depth_conv.conv.weight',
 'module.features.0.0.point_linear.conv.weight',
 'module.features.0.1.inverted_bottleneck.conv.weight',
 'module.features.0.1.depth_conv.conv.weight',
 'module.features.0.1.point_linear.conv.weight',
 'module.features.0.2.inverted_bottleneck.conv.weight',
 'module.features.0.2.depth_conv.conv.weight',
 'module.features.0.2.point_linear.conv.weight',
 'module.features.0.3.inverted_bottleneck.conv.weight',
 'module.features.0.3.depth_conv.conv.weight',
 'module.features.0.3.point_linear.conv.weight',
 'module.features.0.4.inverted_bottleneck.conv.weight',
 'module.features.0.4.depth_conv.conv.weight',
 'module.features.0.4.point_linear.conv.weight',
 'module.features.0.5.inverted_bottleneck.conv.weight',
 'module.features.0.5.depth_conv.conv.weight',

In [30]:
pretrained_key_list

['module.first_conv.conv.weight',
 'module.first_block_conv.depth_conv.conv.weight',
 'module.first_block_conv.point_linear.conv.weight',
 'module.features.0.0.inverted_bottleneck.conv.weight',
 'module.features.0.0.depth_conv.conv.weight',
 'module.features.0.0.point_linear.conv.weight',
 'module.features.0.1.inverted_bottleneck.conv.weight',
 'module.features.0.1.depth_conv.conv.weight',
 'module.features.0.1.point_linear.conv.weight',
 'module.features.0.2.inverted_bottleneck.conv.weight',
 'module.features.0.2.depth_conv.conv.weight',
 'module.features.0.2.point_linear.conv.weight',
 'module.features.0.3.inverted_bottleneck.conv.weight',
 'module.features.0.3.depth_conv.conv.weight',
 'module.features.0.3.point_linear.conv.weight',
 'module.features.0.4.inverted_bottleneck.conv.weight',
 'module.features.0.4.depth_conv.conv.weight',
 'module.features.0.4.point_linear.conv.weight',
 'module.features.0.5.inverted_bottleneck.conv.weight',
 'module.features.0.5.depth_conv.conv.weight',

In [33]:
'module.' + 'first_conv.conv.weight' in torch.load('logs/baseline2/final_network.pth').keys()

True

In [36]:
model = MobileNetV2_search()

In [38]:
trained_model = torch.load(f'logs/baseline2/final_network.pth')
current_dict = model.state_dict()

pretrain_load = 0
for key in current_dict.keys():
    if 'module.' + key in trained_model.keys():
        current_dict[key].copy_(trained_model['module.' + key])
        pretrain_load += 1

model.load_state_dict(current_dict)
print(pretrain_load)

384


In [39]:
model.state_dict()['first_conv.conv.weight']

tensor([[[[-3.4135e-02,  5.5735e-02,  8.8404e-02],
          [ 1.7712e-01,  6.5656e-01,  6.6747e-01],
          [ 2.0492e-01,  7.1888e-01,  6.7735e-01]],

         [[ 6.8576e-02, -2.0557e-01, -2.2023e-01],
          [-9.7463e-02, -3.1686e-01, -3.5672e-01],
          [ 2.5280e-02, -6.8306e-02, -1.6665e-01]],

         [[ 7.8855e-02,  3.8043e-02,  1.3397e-01],
          [-2.5815e-01, -4.3975e-01, -3.9005e-01],
          [-3.3877e-01, -5.0529e-01, -5.7885e-01]]],


        [[[ 1.5859e-01,  1.5920e-01,  1.8378e-01],
          [ 3.9206e-01,  4.3925e-01,  3.8141e-01],
          [ 2.4505e-01,  3.4921e-01,  4.0125e-01]],

         [[-2.9316e-01, -3.8502e-01, -2.8473e-01],
          [-5.6140e-01, -7.5700e-01, -7.7016e-01],
          [-5.6782e-01, -7.2717e-01, -7.2080e-01]],

         [[ 8.9446e-02,  1.3340e-01,  9.3029e-02],
          [ 3.0182e-01,  4.5079e-01,  3.2117e-01],
          [ 2.5648e-01,  4.7142e-01,  3.9228e-01]]],


        [[[-3.2472e-02,  6.6302e-02, -1.5638e-01],
          [ 4.5

In [40]:
trained_model['module.first_conv.conv.weight']

tensor([[[[-3.4135e-02,  5.5735e-02,  8.8404e-02],
          [ 1.7712e-01,  6.5656e-01,  6.6747e-01],
          [ 2.0492e-01,  7.1888e-01,  6.7735e-01]],

         [[ 6.8576e-02, -2.0557e-01, -2.2023e-01],
          [-9.7463e-02, -3.1686e-01, -3.5672e-01],
          [ 2.5280e-02, -6.8306e-02, -1.6665e-01]],

         [[ 7.8855e-02,  3.8043e-02,  1.3397e-01],
          [-2.5815e-01, -4.3975e-01, -3.9005e-01],
          [-3.3877e-01, -5.0529e-01, -5.7885e-01]]],


        [[[ 1.5859e-01,  1.5920e-01,  1.8378e-01],
          [ 3.9206e-01,  4.3925e-01,  3.8141e-01],
          [ 2.4505e-01,  3.4921e-01,  4.0125e-01]],

         [[-2.9316e-01, -3.8502e-01, -2.8473e-01],
          [-5.6140e-01, -7.5700e-01, -7.7016e-01],
          [-5.6782e-01, -7.2717e-01, -7.2080e-01]],

         [[ 8.9446e-02,  1.3340e-01,  9.3029e-02],
          [ 3.0182e-01,  4.5079e-01,  3.2117e-01],
          [ 2.5648e-01,  4.7142e-01,  3.9228e-01]]],


        [[[-3.2472e-02,  6.6302e-02, -1.5638e-01],
          [ 4.5